import React, { useEffect, useState } from 'react';
import { X, Sun, CheckCircle2, AlertCircle, Calendar, Sparkles } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

import { ChevronRight } from 'lucide-react';

interface MorningBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function MorningBriefModal({ isOpen, onClose }: MorningBriefModalProps) {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [briefing, setBriefing] = useState<any>(null);

  useEffect(() => {
    if (isOpen) {
      // Simulate API call to Module 21 (Morning Briefing Engine)
      setLoading(true);
      setTimeout(() => {
        setBriefing({
          greeting: `Good morning, ${user?.name?.split(' ')[0] || 'Dr.'}! ☀️`,
          subGreeting: "Welcome to a new day at PRAJNA.",
          summary: "Here is your personalized briefing for today. You have a busy schedule ahead, but you're making excellent progress on your research goals. Let's make it a great day!",
          agenda: [
            { icon: Calendar, text: "3 Classes Scheduled", type: "neutral", time: "Starts 9:00 AM" },
            { icon: AlertCircle, text: "1 Pending Approval (Due Today)", type: "urgent", time: "By 5:00 PM" },
            { icon: CheckCircle2, text: "FDP Certificate Verified (+20 PRAJNA Points)", type: "success", time: "Completed" }
          ],
          aiInsight: "💡 Pragati Insight: You are only 15 points away from reaching the 'PRAJNA Fellow' tier. Uploading your recent conference presentation will push you over the edge!"
        });
        setLoading(false);
      }, 1500);
    }
  }, [isOpen, user]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-surface border border-white/20 w-full max-w-lg rounded-[2rem] shadow-2xl overflow-hidden animate-in zoom-in-90 duration-500 ease-out">
        {/* Header Graphic */}
        <div className="bg-gradient-to-br from-indigo-600 via-primary to-emerald-500 p-8 text-white relative overflow-hidden">
          {/* Animated Background Elements */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 animate-pulse" />
          <div className="absolute bottom-0 left-0 w-48 h-48 bg-emerald-400/20 rounded-full blur-2xl translate-y-1/3 -translate-x-1/4" />
          
          <button 
            onClick={onClose}
            className="absolute top-4 right-4 text-white/70 hover:text-white transition-colors hover:rotate-90 duration-300"
          >
            <X size={24} />
          </button>
          
          <div className="flex items-center gap-3 mb-3 relative z-10">
            <Sun size={28} className="text-amber-300 animate-[spin_10s_linear_infinite]" />
            <h2 className="text-2xl font-black tracking-wide text-transparent bg-clip-text bg-gradient-to-r from-white to-white/70">Morning Briefing</h2>
          </div>
          <div className="flex items-center gap-2 relative z-10">
            <Sparkles size={14} className="text-amber-200" />
            <p className="text-white/90 text-sm font-semibold tracking-wide">Generated by Pragati AI</p>
          </div>
        </div>

        {/* Content */}
        <div className="p-8">
          {loading ? (
            <div className="space-y-6 animate-pulse">
              <div className="h-8 bg-black/5 dark:bg-white/5 rounded-lg w-2/3" />
              <div className="h-4 bg-black/5 dark:bg-white/5 rounded w-full" />
              <div className="h-4 bg-black/5 dark:bg-white/5 rounded w-5/6" />
              <div className="pt-6 space-y-4">
                <div className="h-16 bg-black/5 dark:bg-white/5 rounded-2xl w-full" />
                <div className="h-16 bg-black/5 dark:bg-white/5 rounded-2xl w-full" />
              </div>
            </div>
          ) : (
            <div className="space-y-8 animate-in slide-in-from-bottom-4 duration-700 ease-out fade-in fill-mode-both">
              <div>
                <h3 className="text-2xl font-black text-text mb-1 bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent">{briefing.greeting}</h3>
                <p className="text-text font-bold mb-3">{briefing.subGreeting}</p>
                <p className="text-textMuted text-sm leading-relaxed">{briefing.summary}</p>
              </div>

              <div className="space-y-3">
                <h4 className="text-xs font-bold text-text uppercase tracking-widest mb-4">Today's Agenda</h4>
                {briefing.agenda.map((item: any, i: number) => {
                  const Icon = item.icon;
                  const colorClass = 
                    item.type === 'urgent' ? 'text-rose-500 bg-rose-500/10 border-rose-500/20' :
                    item.type === 'success' ? 'text-emerald-500 bg-emerald-500/10 border-emerald-500/20' :
                    'text-indigo-500 bg-indigo-500/10 border-indigo-500/20';
                  
                  return (
                    <div 
                      key={i} 
                      className="flex items-center gap-4 p-4 rounded-2xl border bg-surface hover:shadow-md transition-all duration-300 animate-in slide-in-from-bottom-2 fade-in hover:-translate-y-1"
                      style={{ animationDelay: \`\${(i + 1) * 150}ms\`, animationFillMode: 'both' }}
                    >
                      <div className={\`w-10 h-10 rounded-xl flex items-center justify-center \${colorClass}\`}>
                        <Icon size={20} />
                      </div>
                      <div className="flex-1">
                        <span className="block text-sm font-bold text-text">{item.text}</span>
                        <span className="block text-xs text-textMuted mt-0.5">{item.time}</span>
                      </div>
                      <ChevronRight size={16} className="text-border" />
                    </div>
                  );
                })}
              </div>

              <div 
                className="bg-gradient-to-r from-primary/10 to-accent/10 border border-primary/20 rounded-2xl p-5 animate-in slide-in-from-bottom-4 fade-in"
                style={{ animationDelay: '600ms', animationFillMode: 'both' }}
              >
                <p className="text-sm font-semibold text-primary leading-relaxed flex items-start gap-2">
                  <span className="text-lg">💡</span>
                  <span>{briefing.aiInsight}</span>
                </p>
              </div>

              <button 
                onClick={onClose}
                className="w-full py-4 bg-gradient-to-r from-primary to-accent text-white font-black text-lg rounded-2xl hover:scale-[1.02] active:scale-95 transition-all shadow-xl shadow-primary/25 animate-in fade-in"
                style={{ animationDelay: '800ms', animationFillMode: 'both' }}
              >
                Let's Get Started 🚀
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
