import React, { useEffect, useState } from 'react';
import { X, Sun, CheckCircle2, AlertCircle, Calendar } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

interface MorningBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function MorningBriefModal({ isOpen, onClose }: MorningBriefModalProps) {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [briefing, setBriefing] = useState<any>(null);

  useEffect(() => {
    if (isOpen) {
      // Simulate API call to Module 21 (Morning Briefing Engine)
      setLoading(true);
      setTimeout(() => {
        setBriefing({
          greeting: `Good morning, ${user?.name?.split(' ')[0] || 'Dr.'}! ☀️`,
          summary: "Here is your personalized PRAJNA briefing for today. You have a busy schedule ahead, but you're making excellent progress on your research goals.",
          agenda: [
            { icon: Calendar, text: "3 Classes Scheduled", type: "neutral" },
            { icon: AlertCircle, text: "1 Pending Approval (Due Today)", type: "urgent" },
            { icon: CheckCircle2, text: "FDP Certificate Verified (+20 PRAJNA Points)", type: "success" }
          ],
          aiInsight: "💡 Pragati Insight: You are only 15 points away from reaching the 'PRAJNA Fellow' tier. Uploading your recent conference presentation will push you over the edge!"
        });
        setLoading(false);
      }, 1500);
    }
  }, [isOpen, user]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-surface border border-border w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300">
        {/* Header Graphic */}
        <div className="bg-gradient-to-br from-primary to-accent p-6 text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2" />
          
          <button 
            onClick={onClose}
            className="absolute top-4 right-4 text-white/70 hover:text-white transition-colors"
          >
            <X size={20} />
          </button>
          
          <div className="flex items-center gap-3 mb-2">
            <Sun size={24} className="text-amber-300" />
            <h2 className="text-xl font-black tracking-wide">Morning Briefing</h2>
          </div>
          <p className="text-white/80 text-sm font-medium">Generated by Pragati AI</p>
        </div>

        {/* Content */}
        <div className="p-6">
          {loading ? (
            <div className="space-y-4 animate-pulse">
              <div className="h-6 bg-border rounded w-1/2" />
              <div className="h-4 bg-border rounded w-full" />
              <div className="h-4 bg-border rounded w-5/6" />
              <div className="pt-4 space-y-3">
                <div className="h-10 bg-border rounded w-full" />
                <div className="h-10 bg-border rounded w-full" />
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-bold text-text mb-2">{briefing.greeting}</h3>
                <p className="text-textMuted text-sm leading-relaxed">{briefing.summary}</p>
              </div>

              <div className="space-y-3">
                <h4 className="text-xs font-bold text-text uppercase tracking-wider">Today's Agenda</h4>
                {briefing.agenda.map((item: any, i: number) => {
                  const Icon = item.icon;
                  const colorClass = 
                    item.type === 'urgent' ? 'text-rose-500 bg-rose-500/10' :
                    item.type === 'success' ? 'text-emerald-500 bg-emerald-500/10' :
                    'text-primary bg-primary/10';
                  
                  return (
                    <div key={i} className="flex items-center gap-3 p-3 rounded-xl border border-border">
                      <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${colorClass}`}>
                        <Icon size={16} />
                      </div>
                      <span className="text-sm font-bold text-text">{item.text}</span>
                    </div>
                  );
                })}
              </div>

              <div className="bg-primary/5 border border-primary/20 rounded-xl p-4">
                <p className="text-sm font-medium text-primary leading-relaxed">
                  {briefing.aiInsight}
                </p>
              </div>

              <button 
                onClick={onClose}
                className="w-full py-3 bg-primary text-white font-bold rounded-xl hover:bg-primary/90 transition-colors shadow-lg shadow-primary/20"
              >
                Let's Get Started
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
